[project]
name = "Zero"
authors = [ "Zero Day Code" ]
compilation_db = true
project_root = "zero"

[compiler]
cpp_compiler = "clang"
cpp_standard = "20"
std_lib = "LIBCPP"

[build]
output_dir = "./out"

[executable]
executable_name = "zero"
sources = [ "*.cpp" ]

[tests]
tests_executable_name = "zero_tests"
sources = [ "tests/**/*.cpp" ]

[modules]
sys_modules = ['cstdio']
base_ifcs_dir = "ifc"
interfaces = [
    { file = 'commons/typedefs.cppm' },    
    { file = 'text/str_manip.cppm' },
    { file = 'types/type_info.cppm' },
    { file = 'types/type_traits.cppm' },
    { file = 'commons/concepts.cppm', dependencies = ['typedefs'] },

    ### Iterator library
    { file = 'iterators/internal/iterator_detail.cpp', partition = { module = 'iterator', partition_name = 'detail' } },
    { file = 'iterators/iterator_concepts.cppm', partition = { module = 'iterator', partition_name = 'concepts' } },
    # Modern
    { file = 'iterators/iterator_facade.cppm', partition = { module = 'iterator' } },
    { file = 'iterators/input_iterator.cppm', partition = { module = 'iterator' } },
    # Legacy
    { file = 'iterators/legacy/legacy_iterator.cppm', partition = { module = 'iterator' } },
    { file = 'iterators/legacy/legacy_input_iterator.cppm', partition = { module = 'iterator' } },
    { file = 'iterators/legacy/legacy_output_iterator.cppm', partition = { module = 'iterator' } },
    # Root
    { file = 'iterators/iterator.cppm' },

    # The collections/containers librar
    { file = 'collections/container.cppm', dependencies = ['type_info'] },
    { file = 'collections/array.cppm', dependencies = ['typedefs', 'concepts', 'iterator', 'container'] },
    { file = 'collections/collections.cppm', dependencies = ['array'] },
    
    # The physics library
    { file = 'physics/quantities/internal/units_detail.cpp', partition = { module = 'physics', partition_name = 'units.detail' } },

    { file = 'physics/quantities/ratios.cppm', partition = { module = 'physics' } },
    { file = 'physics/quantities/units.symbols.cppm', module_name = 'units.symbols', partition = { module = 'physics' } },
    { file = 'physics/quantities/dimensions.cppm', module_name = 'dimensions', partition = { module = 'physics' } },
    { file = 'physics/quantities/units.cppm', module_name = 'units', partition = { module = 'physics' } },
    { file = 'physics/quantities/quantity.cppm', partition = { module = 'physics' }, dependencies = ['physics-ratios', 'physics-units', 'physics-units.symbols'] },
    # Root
    { file = 'physics/physics.cppm' },

    # The main interface of the project
    { file = 'zero.cppm' }
]

